<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-9R6Q1BR" failures="1" tests="1" name="Default test" time="43.933" errors="0" timestamp="2024-10-13T16:42:30 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="41.155">
    <failure type="java.lang.AssertionError" message="expected [THANKYOU FOR THE ORDER] but found [THANKYOU FOR THE ORDER.]">
      <![CDATA[java.lang.AssertionError: expected [THANKYOU FOR THE ORDER] but found [THANKYOU FOR THE ORDER.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at SeleniumUdemyLearning.StepDefinitionImplementation.message_confirmation(StepDefinitionImplementation.java:52)
at âœ½."THANKYOU FOR THE ORDER" message is displayed on confirmationPage(file:///C:/Users/MY%20BOOK/eclipse-workspace/SeleniumFrameworkDesign/src/test/java/CucumberTest/PurchaseOrder.feature:30)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
